#!/bin/sh -e

. /lib/grub-mkconfig_lib

for file in memtest86+ memtest86; do
if test -e /boot/$file; then
	MEMTESTPATH=$( make_system_path_relative_to_its_root "/boot/$file" )
	echo "Found $file image: $MEMTESTPATH" >&2
	cat << EOF
menuentry "Memory test ($file)" {
	linux	$MEMTESTPATH
}
EOF
fi
done
